version: '3.4'

services:
  # server-api:
  #   build: .
  #   environment:
  #     POSTGRES_HOST: postgres
  #     POSTGRES_PORT: 5432
  #     MONGO_HOST: mongo
  #     MONGO_PORT: 27017
  #   ports:
  #     - 3334:3333
  #   depends_on:
  #     - postgres
  #     - mongo
  #     - redis

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gostack_gobarber
    ports:
      - 5433:5432

  mongo:
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: mongo
    #   MONGO_INITDB_ROOT_PASSWORD: docker

    ports:
      - 27018:27017

  redis:
    image: redis
    restart: always
    ports:
      - 6380:6379
